;; -*- mode: emacs-lisp; lexical-binding: t; coding: utf-8-emacs-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(file-name-history))
(setq file-name-history '("~/code/new-machine-setup/ansible/roles/dotfiles/templates/.zshrc.j2"))
